db-uri = "postgres://postgres:postgres@postgres:5432/coffee_shop_db"
db-schema = "public"
db-anon-role = "web_anon"
server-host = "0.0.0.0"
server-port = 3000
jwt-secret = "supersecretjwtsecret"
db-pool = 10
openapi-mode = "follow-privileges"
